// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef LABSoft_GUI_Logic_Analyzer_Display_h
#define LABSoft_GUI_Logic_Analyzer_Display_h
#include <FL/Fl.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Browser.H>
#include <FL/Fl_Menu_Button.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Button.H>

class UserInterface : public Fl_Group {
public:
  UserInterface(int X, int Y, int W, int H, const char *L = 0);
  Fl_Group *time_per_division_labels_strip;
  Fl_Group *top_info_strip;
  Fl_Group *channel widget;
  Fl_Group *m_fl_group_channel_info;
  Fl_Output *m_fl_output_name;
  Fl_Button *m_button_channel_info_setting;
  Fl_Output *m_fl_output_dio_pin;
  Fl_Menu_Button *m_fl_menu_button_trigger_mode;
  static Fl_Menu_Item menu_m_fl_menu_button_trigger_mode[];
  Fl_Group *m_fl_widget_channel_graph;
};
#endif
