// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef LABSoft_GUI_Oscilloscope_Display_h
#define LABSoft_GUI_Oscilloscope_Display_h
#include <FL/Fl.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Slider.H>

class labsoft_gui_oscilloscope_display : public LABSoft_GUI_Oscilloscope_Display {
public:
  labsoft_gui_oscilloscope_display(int X, int Y, int W, int H, const char *L = 0);
  Fl_Box *c1 vpd unit;
  Fl_Box *c2 vpd unit;
  Fl_Box *c1 volts per div first;
  Fl_Box *c2 volts per div first;
  Fl_Box *c1 volts per div mid;
  Fl_Box *c2 volts per div mid;
  Fl_Box *c1 volts per div last;
  Fl_Box *c2 volts per div last;
  Fl_Box *time per div first;
  Fl_Box *time per div mid;
  Fl_Box *time per div last;
};
#endif
