// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef LABSoft_GUI_Logic_Analyzer_Add_Channel_Window_h
#define LABSoft_GUI_Logic_Analyzer_Add_Channel_Window_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Browser.H>
#include <FL/Fl_Button.H>

class LABSoft_GUI_Logic_Analyzer_Add_Channel_Window {
public:
  LABSoft_GUI_Logic_Analyzer_Add_Channel_Window();
};
#endif
